services:
  app:
    build: .
    ports:
      - "13000:3000"
    environment: # overrides the default from env file
      MONGODB_URL: "mongodb://db:27017/thss-forum"
      REDIS_URL: "redis://redis:6379"
  db:
    image: mongo:latest
    volumes:
      - thss-forum-db:/data/db
  redis:
    image: redis:latest
volumes:
  thss-forum-db:
